<a href="https://colab.research.google.com/github/aparna-2001/computational_math_toolkit/blob/main/PCA_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PCA ANALYSIS**



*   PCA reduces the redundant data and only keeps the essential informative data




In [6]:
#Data for PCA analysis

import numpy as np
import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Math": [85, 78, 92, 70, 88],
    "Physics": [80, 75, 88, 68, 84],
    "Chemistry": [82, 77, 90, 69, 86]
}

#let's convert this data to matrix

data_table = pd.DataFrame(data)
data_table_numpy = data_table.to_numpy()
print(data_table)


data_matrix = data_table_numpy[:, 1:]
print(data_matrix)



  Student  Math  Physics  Chemistry
0       A    85       80         82
1       B    78       75         77
2       C    92       88         90
3       D    70       68         69
4       E    88       84         86
[[85 80 82]
 [78 75 77]
 [92 88 90]
 [70 68 69]
 [88 84 86]]


In [27]:
#Data for PCA analysis

import numpy as np
import pandas as pd

data = {
    "Student": ["A", "B", "C", "D", "E"],
    "Math": [85, 78, 92, 70, 88],
    "Physics": [80, 75, 88, 68, 84],
    "Chemistry": [82, 77, 90, 69, 86]
}

#let's convert this data to matrix

data_table = pd.DataFrame(data)
data_table_numpy = data_table.to_numpy()
data_matrix = data_table_numpy[:, 1:].astype(float) # Cast to float here
print(data_matrix)

#mean of each column

mean_col_1 = np.mean(data_matrix[:,0])
print(mean_col_1)
mean_col_2 = np.mean(data_matrix[:,1])
print(mean_col_2)
mean_col_3 = np.mean(data_matrix[:,2])
print(mean_col_3)


#substracting the mean from each column

mean_centered = data_matrix - np.array([[mean_col_1,mean_col_2,mean_col_3]])
print(mean_centered)

#finding the covariance of the matrix

covariance_matrix = np.cov(mean_centered, rowvar=False) # rowvar=False because each row is an observation
print(covariance_matrix)

#Eigen values and Eigen vectors

eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
print(f"Eigen values of of the matrix: {eigenvalues}",'\n')
print(f"Eigen vectors of of the matrix: {eigenvectors}",'\n')

#sorting Eigen values in descending order

sorted_eigen_values = np.argsort(eigenvalues)[::-1]
print(f"The eigen values in descending order: {sorted_eigen_values}",'\n')

#reorder eigen values and eigen vectors

eigen_values_ordered = eigenvalues[sorted_eigen_values]
eigen_vectors_ordered = eigenvectors[:,sorted_eigen_values]

print(f"The ordered Eigen values are: {eigen_values_ordered}")
print(f"The ordered Eigen vectors are: {eigen_vectors_ordered}")


[[85. 80. 82.]
 [78. 75. 77.]
 [92. 88. 90.]
 [70. 68. 69.]
 [88. 84. 86.]]
82.6
79.0
80.8
[[  2.4   1.    1.2]
 [ -4.6  -4.   -3.8]
 [  9.4   9.    9.2]
 [-12.6 -11.  -11.8]
 [  5.4   5.    5.2]]
[[75.8  67.75 70.9 ]
 [67.75 61.   63.75]
 [70.9  63.75 66.7 ]]
Eigen values of of the matrix: [2.03168181e+02 2.98767433e-01 3.30518750e-02] 

Eigen vectors of of the matrix: [[-0.61006295 -0.78745253 -0.08798701]
 [-0.5475436   0.4992334  -0.67153706]
 [-0.57272961  0.36150316  0.73572839]] 

The eigen values in descending order: [0 1 2] 

The ordered Eigen values are: [2.03168181e+02 2.98767433e-01 3.30518750e-02]
The ordered Eigen vectors are: [[-0.61006295 -0.78745253 -0.08798701]
 [-0.5475436   0.4992334  -0.67153706]
 [-0.57272961  0.36150316  0.73572839]]


**PCA inference**



*   the largest Eigen value is 203.17 approximately
     - which means since there is only one large Eigen value, and other values are less and negligible;
          - we can say that the data can be reduced to one dimension
              - that is we need to consider only one principal component analysis value to gather inference for the data
                 - for that we need to take the eigen vectors corresponding to the largest eigen value.



In [39]:

PCA_1_vector_array = eigen_vectors_ordered[:, 0].reshape(1, -1)

#print(PCA_1_vector_array,'\n')

PCA_1_vector_T = PCA_1_vector_array.T
#print(PCA_1_vector_T)

#print(PCA_1_vector_array.shape)
#print(PCA_1_vector_T.shape)

#print(mean_centered)

student_PC1_scores = mean_centered@PCA_1_vector_T
print(student_PC1_scores)

[[ -2.69897021]
 [  7.17283648]
 [-15.93159652]
 [ 20.46798214]
 [ -9.01025189]]


**Output inference**



*   Here the output number indicates that;
     - The most positive number corresponds to 4th row, that is STUDENT D.
         - student D is the best performer
    - The most negative number corresponds to 3rd row, that is STUDENT C.
         -STUDENT C shows the poorest performance

