<a href="https://colab.research.google.com/github/aparna-2001/computational_math_toolkit/blob/main/python_matrix_%26_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Don't let the code and numbers clump your mind**

-Don't bother too much on the naming of variables

-It doesn't matter wether it is matrix_1 or matrix_2 or any words or numbers

-consider it as just as containers

-Play with the variables

-focus on the details on right side than left side

-change variables name according to your desire



In [ ]:
#creating a matrix in python

matrix_1 = [[2,1],[3,4]]
matrix_2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [9]:
#creating a matrix from data

data_1 = {"sample":["s1","s2","s3"],
          "gene_1":[1,2,3],
          "gene_2":[4,5,6],
          "gene_3":[7,8,9]}

#converting this to table

import pandas as pd
table_1 = pd.DataFrame(data_1)
print(table_1)

#converting the table to matrix

matrix_4 = table_1.to_numpy()
print(matrix_4)


  sample  gene_1  gene_2  gene_3
0     s1       1       4       7
1     s2       2       5       8
2     s3       3       6       9
[['s1' 1 4 7]
 ['s2' 2 5 8]
 ['s3' 3 6 9]]


In [7]:
#practice yourself
#convert the below data to matrix
   #first to table and then to matrix

data = {
    "sample": ["A", "B", "C", "D"],
    "gene_1": [5, 3, 6, 2],
    "gene_2": [7, 4, 5, 1],
    "gene_3": [8, 2, 7, 3]
}




  sample  gene_1  gene_2  gene_3
0      A       5       7       8
1      B       3       4       2
2      C       6       5       7
3      D       2       1       3
[['A' 5 7 8]
 ['B' 3 4 2]
 ['C' 6 5 7]
 ['D' 2 1 3]]


In [10]:
#answer

#converting to table

import pandas as pd
table_2 = pd.DataFrame(data)
print(table_2)

#converting to matrix

matrix_5 = table_2.to_numpy()
print(matrix_5)


  sample  gene_1  gene_2  gene_3
0      A       5       7       8
1      B       3       4       2
2      C       6       5       7
3      D       2       1       3
[['A' 5 7 8]
 ['B' 3 4 2]
 ['C' 6 5 7]
 ['D' 2 1 3]]


In [15]:
#another dataset
#converting to matrix

data_behavior = {
    "participant": ["P1", "P2", "P3", "P4"],
    "reaction_time_ms": [350, 420, 300, 390],
    "accuracy_percent": [95, 88, 100, 92],
    "trial_count": [10, 12, 9, 11]
}

#converting to table

import pandas as pd
table_3 = pd.DataFrame(data_behavior)
print(table_3)

#converting to matrix
matrix_6 = table_3.to_numpy()
print(matrix_6)

#for only generating numerical matrix
matrix_7 = table_3[["reaction_time_ms","accuracy_percent","trial_count"]].to_numpy()
print(matrix_7)

  participant  reaction_time_ms  accuracy_percent  trial_count
0          P1               350                95           10
1          P2               420                88           12
2          P3               300               100            9
3          P4               390                92           11
[['P1' 350 95 10]
 ['P2' 420 88 12]
 ['P3' 300 100 9]
 ['P4' 390 92 11]]
[[350  95  10]
 [420  88  12]
 [300 100   9]
 [390  92  11]]


In [23]:
#finding the order of matrix

import numpy as np

matrix_1 = [[2,1],[3,4]]

#finding the order of matrix

matrix_1_order = np.array(matrix_1)
print(matrix_1_order.shape)


(2, 2)


In [24]:
#more practice on finding order

import numpy as np

matrix_2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

#finding order

matrix_2_order = np.array(matrix_2)
print(matrix_2_order.shape)

matrix_2_order = np.array(matrix_2)
print(matrix_2_order.shape)



(3, 3)
(3, 3)


In [25]:
# for more clear ouput generation;
   #provide text to specify each matrix order

import numpy as np

matrix_2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

#finding order

matrix_2_order = np.array(matrix_2)
print(f"order of matrix_2: {matrix_2_order.shape}")

matrix_3_order = np.array(matrix_3)
print(f"order of matrix_3: {matrix_3_order.shape}")


order of matrix_2: (3, 3)
order of matrix_3: (4, 4)


In [30]:
#calculating the determinant of a matrix

import numpy as np

#here we are using 'linalg'module in numpy

matrix_2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_2 = np.array(matrix_2)

det = np.linalg.det(matrix_2)
print(f"Determinant of matrix_2: {det}")


Determinant of matrix_2: 0.0


In [32]:
#find the determinant of the below data
  #the matrix has been already generated


data_1 = {"sample":["s1","s2","s3"],
          "gene_1":[1,2,3],
          "gene_2":[4,5,6],
          "gene_3":[7,8,9]}

#converting this to table

import pandas as pd
table_1 = pd.DataFrame(data_1)
print(table_1)

#converting the table to matrix

matrix_4 = table_1[["gene_1","gene_2","gene_3"]].to_numpy()
print(matrix_4)

#FIND THE DETERMINANT OF matrix_4

import numpy as np
matrix_4 = np.array(matrix_4)
matrix_4_det = np.linalg.det(matrix_4)
print(f"Determinant of matrix_4: {matrix_4_det}")


  sample  gene_1  gene_2  gene_3
0     s1       1       4       7
1     s2       2       5       8
2     s3       3       6       9
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinant of matrix_4: 0.0


**Since we found the determinant, what does the this determinat value actually means?**



*  If det is zero, which means rows/columns are linearly dependent
*  so only with matrix with rows/colums that are linearly independent has non zero determinat

*What would this dependent/independent mean in a data?*

Let's take our above code, (cell 32);
    - There the determinant is zero
        - which means the data may not be linearly independent
             - it may be linearly dependent
                  - they depend each other



**caution**: Only with determinat only we cannot say a data is correlated/dependent in real world problems



In [34]:
#another dataset
#converting to matrix

data_behavior = {
    "participant": ["P1", "P2", "P3", "P4"],
    "reaction_time_ms": [350, 420, 300, 390],
    "accuracy_percent": [95, 88, 100, 92],
    "trial_count": [10, 12, 9, 11]
}

#converting to table

import pandas as pd
table_3 = pd.DataFrame(data_behavior)
print(table_3)

#converting to matrix
matrix_6 = table_3.to_numpy()
print(matrix_6)

#for only generating numerical matrix
matrix_7 = table_3[["reaction_time_ms","accuracy_percent","trial_count"]].to_numpy()
print(matrix_7)
print(f"Order of the matrix_7: {matrix_7.shape}")

import numpy as np


#finding the determinant
matrix_7 = np.array(matrix_7)
matrix_7_det = np.linalg.det(matrix_7)
print(f"Determinant of matrix_7: {matrix_7_det}")


  participant  reaction_time_ms  accuracy_percent  trial_count
0          P1               350                95           10
1          P2               420                88           12
2          P3               300               100            9
3          P4               390                92           11
[['P1' 350 95 10]
 ['P2' 420 88 12]
 ['P3' 300 100 9]
 ['P4' 390 92 11]]
[[350  95  10]
 [420  88  12]
 [300 100   9]
 [390  92  11]]
Order of the matrix_7: (4, 3)


LinAlgError: Last 2 dimensions of the array must be square

**Oops! Error right!**

We should be aware that only square matrices has detrminants.

In the above practice, the matrix has the order of 4,3. so we cannot find the determinant

*small advice: Don't erase the determinant code just because you see some error in your output. Let it be. Errors are good. It will refresh your basics when you look at the code after some time*

In [ ]:
#we can use 'linalg' module to find many features of a matrix(or data)
   #

import numpy as np

