<a href="https://colab.research.google.com/github/aparna-2001/computational_math_toolkit/blob/main/python_matrix_%26_operations_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

#part1 practice/tutroial link:https://github.com/aparna-2001/computational_math_toolkit/blob/main/python_matrix_%26_operations_part1.ipynb


In [4]:
#let's solve for x and y values

import sympy as sp
from sympy import Eq, symbols, linear_eq_to_matrix, solve

x,y = symbols('x y')

eqn_1 = Eq(2*x + 3*y,8)
eqn_2 = Eq(1*x - 1*y,1)

eqn_solutions = solve((eqn_1, eqn_2),(x,y))
print(eqn_solutions)

{x: 11/5, y: 6/5}


In [ ]:
#What if we want to convert the linear equation to matrix



#we are using a new package called sympy
  #for the conversion of linear equations to matrix


from sympy import symbols, Eq, linear_eq_to_matrix

x, y = symbols('x y')

eqn_1 = Eq(2*x + 3*y, 8)
eqn_2 = Eq(5*x + 4*y, 13)

eqn_1_matrix = linear_eq_to_matrix([eqn_1],[x,y])
eqn_2_matrix = linear_eq_to_matrix([eqn_2], [x,y])

print(f"matrix of eqn_1: {eqn_1_matrix}")
print(f"matrix of eqn 2: {eqn_2_matrix}")

matrix of eqn_1: (Matrix([[2, 3]]), Matrix([[8]]))
matrix of eqn 2: (Matrix([[5, 4]]), Matrix([[13]]))


In [ ]:
# To solve linear equation it is not much use writing as separate matrices

#let's merge it to one matrix

from sympy import Eq, symbols, linear_eq_to_matrix

x, y = symbols('x y')

eqn_1 = Eq(2*x + 3*y, 8)
eqn_2 = Eq(5*x + 4*y, 13)


#combining everything here

eqn_matrix_with_coeff, eqn_matrix_without_coeff = linear_eq_to_matrix([eqn_1, eqn_2],[x,y])

print(eqn_matrix_with_coeff)
print(eqn_matrix_without_coeff)



Matrix([[2, 3], [5, 4]])
Matrix([[8], [13]])


In [7]:
#let's see if can go for a long route to solve the eqn
  # solving after converting to the matrix

import sympy as sp
from sympy import Eq, symbols, linear_eq_to_matrix

x,y = symbols('x y')

eqn_1 = Eq(2*x + 3*y,8)
eqn_2 = Eq(1*x - 1*y,1)

eqn_matrix_with_coeff, eqn_matrix_without_coeff = linear_eq_to_matrix([eqn_1, eqn_2],[x,y])

#solving the equation

solution = eqn_matrix_with_coeff.LUsolve((eqn_matrix_without_coeff))

solution = {x: solution[0], y: solution[1]}
print(solution)



{x: 11/5, y: 6/5}


In [10]:
#how to create a vector


data = [['i','j','k'],[1, 2, 3],[5, 6 , 7]]

In [14]:
#how to create a vector

import numpy as np
import pandas as pd


data = {'i':[2, 3, 4],
         'j':[6,7, 5],
        'k': [8,3, 7]}

data_table = pd.DataFrame(data)
print(data_table)

data_matrix = np.array(data_table)
print(data_matrix)


   i  j  k
0  2  6  8
1  3  7  3
2  4  5  7
[[2 6 8]
 [3 7 3]
 [4 5 7]]


In [17]:
#finding the dot product

import numpy as np
import pandas as pd


data = {'i':[2, 3, 5],
         'j':[6,7, 6],
        'k': [8,3, 7]}

data_table = pd.DataFrame(data)
print(data_table)

data_matrix = np.array(data_table)
print(data_matrix)

#finding the dot product

a = data_matrix[0]
b = data_matrix[1]

dot_product = np.dot(a,b)
print(dot_product)


   i  j  k
0  2  6  8
1  3  7  3
2  5  6  7
[[2 6 8]
 [3 7 3]
 [5 6 7]]
72


In [18]:
#now let's find the cross product

import numpy as np
import pandas as pd


data = {'i':[2, 3, 5],
         'j':[6,7, 6],
        'k': [8,3, 7]}

data_table = pd.DataFrame(data)
print(data_table)

data_matrix = np.array(data_table)
print(data_matrix)

#finding the cross product

a = data_matrix[0]
b = data_matrix[1]

cross_product = np.cross(a,b)
print(cross_product)


   i  j  k
0  2  6  8
1  3  7  3
2  5  6  7
[[2 6 8]
 [3 7 3]
 [5 6 7]]
[-38  18  -4]


**What does it mean by Dot and cross product**

- Dot product checks the similarity of data

- large positive = high similarity, zero = no similarity, negative = opposite trend

- cross prdouct checks the geometric orientation

In [20]:
#Finding the angle of the vectors from dot product



import numpy as np
import pandas as pd


data = {'i':[2, 3, 5],
         'j':[6,7, 6],
        'k': [8,3, 7]}

data_table = pd.DataFrame(data)
print(data_table)

data_matrix = np.array(data_table)
print(data_matrix)

#finding the cross product

a = data_matrix[0]
b = data_matrix[1]

#finding the angle

cos_theta = np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))
theta = np.arccos(cos_theta)
theta_degree = np.degrees(theta)
print(theta_degree)


   i  j  k
0  2  6  8
1  3  7  3
2  5  6  7
[[2 6 8]
 [3 7 3]
 [5 6 7]]
30.39720275423101


In [ ]:
#finding angle from the cross product

import numpy as np
import pandas as pd


data = {'i':[2, 3, 5],
         'j':[6,7, 6],
        'k': [8,3, 7]}

data_table = pd.DataFrame(data)
print(data_table)

data_matrix = np.array(data_table)
print(data_matrix)

#finding the cross product

a = data_matrix[0]
b = data_matrix[1]

cross_product = np.cross(a,b)
print(cross_product)

#finding the angle

sin theta = np.