<a href="https://colab.research.google.com/github/aparna-2001/computational_math_toolkit/blob/main/python_matrix_%26_operations_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Don't let the code and numbers clump your mind**

-Don't bother too much on the naming of variables

-It doesn't matter wether it is matrix_1 or matrix_2 or any words or numbers

-consider it as just as containers

-Play with the variables

-focus on the details on right side than left side

-change variables name according to your desire

-While using packages usually it is best to keep the import statements above all code, but for learning I have kept it between code for my convenience




  **What we are going to learn**
    
  -How to convert data into matrix

   -How to find the detrminant of that matrix

   -How to find the inverse of that matrix

   -How to find the Eigen values and Eigen vectors of that matrix
   
   -How to find the Rank of that

In [ ]:
#creating a matrix in python

matrix_1 = [[2,1],[3,4]]
matrix_2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [ ]:
#creating a matrix from data

data_1 = {"sample":["s1","s2","s3"],
          "gene_1":[1,2,3],
          "gene_2":[4,5,6],
          "gene_3":[7,8,9]}

#converting this to table

import pandas as pd
table_1 = pd.DataFrame(data_1)
print(table_1)

#converting the table to matrix

matrix_4 = table_1.to_numpy()
print(matrix_4)


  sample  gene_1  gene_2  gene_3
0     s1       1       4       7
1     s2       2       5       8
2     s3       3       6       9
[['s1' 1 4 7]
 ['s2' 2 5 8]
 ['s3' 3 6 9]]


In [ ]:
#practice yourself
#convert the below data to matrix
   #first to table and then to matrix

data = {
    "sample": ["A", "B", "C", "D"],
    "gene_1": [5, 3, 6, 2],
    "gene_2": [7, 4, 5, 1],
    "gene_3": [8, 2, 7, 3]
}




  sample  gene_1  gene_2  gene_3
0      A       5       7       8
1      B       3       4       2
2      C       6       5       7
3      D       2       1       3
[['A' 5 7 8]
 ['B' 3 4 2]
 ['C' 6 5 7]
 ['D' 2 1 3]]


In [ ]:
#answer

#converting to table

import pandas as pd
table_2 = pd.DataFrame(data)
print(table_2)

#converting to matrix

matrix_5 = table_2.to_numpy()
print(matrix_5)


  sample  gene_1  gene_2  gene_3
0      A       5       7       8
1      B       3       4       2
2      C       6       5       7
3      D       2       1       3
[['A' 5 7 8]
 ['B' 3 4 2]
 ['C' 6 5 7]
 ['D' 2 1 3]]


In [ ]:
#another dataset
#converting to matrix

data_behavior = {
    "participant": ["P1", "P2", "P3", "P4"],
    "reaction_time_ms": [350, 420, 300, 390],
    "accuracy_percent": [95, 88, 100, 92],
    "trial_count": [10, 12, 9, 11]
}

#converting to table

import pandas as pd
table_3 = pd.DataFrame(data_behavior)
print(table_3)

#converting to matrix
matrix_6 = table_3.to_numpy()
print(matrix_6)

#for only generating numerical matrix
matrix_7 = table_3[["reaction_time_ms","accuracy_percent","trial_count"]].to_numpy()
print(matrix_7)

  participant  reaction_time_ms  accuracy_percent  trial_count
0          P1               350                95           10
1          P2               420                88           12
2          P3               300               100            9
3          P4               390                92           11
[['P1' 350 95 10]
 ['P2' 420 88 12]
 ['P3' 300 100 9]
 ['P4' 390 92 11]]
[[350  95  10]
 [420  88  12]
 [300 100   9]
 [390  92  11]]


In [ ]:
#finding the order of matrix

import numpy as np

matrix_1 = [[2,1],[3,4]]

#finding the order of matrix

matrix_1_order = np.array(matrix_1)
print(matrix_1_order.shape)


(2, 2)


In [ ]:
#more practice on finding order

import numpy as np

matrix_2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

#finding order

matrix_2_order = np.array(matrix_2)
print(matrix_2_order.shape)

matrix_2_order = np.array(matrix_2)
print(matrix_2_order.shape)



(3, 3)
(3, 3)


In [ ]:
# for more clear ouput generation;
   #provide text to specify each matrix order

import numpy as np

matrix_2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

#finding order

matrix_2_order = np.array(matrix_2)
print(f"order of matrix_2: {matrix_2_order.shape}")

matrix_3_order = np.array(matrix_3)
print(f"order of matrix_3: {matrix_3_order.shape}")


order of matrix_2: (3, 3)
order of matrix_3: (4, 4)


In [ ]:
#calculating the determinant of a matrix

import numpy as np

#here we are using 'linalg'module in numpy

matrix_2 = [[1,2,3],[4,5,6],[7,8,9]]
matrix_2 = np.array(matrix_2)

det = np.linalg.det(matrix_2)
print(f"Determinant of matrix_2: {det}")


Determinant of matrix_2: 0.0


In [ ]:
#find the determinant of the below data
  #the matrix has been already generated


data_1 = {"sample":["s1","s2","s3"],
          "gene_1":[1,2,3],
          "gene_2":[4,5,6],
          "gene_3":[7,8,9]}

#converting this to table

import pandas as pd
table_1 = pd.DataFrame(data_1)
print(table_1)

#converting the table to matrix

matrix_4 = table_1[["gene_1","gene_2","gene_3"]].to_numpy()
print(matrix_4)

#FIND THE DETERMINANT OF matrix_4

import numpy as np
matrix_4 = np.array(matrix_4)
matrix_4_det = np.linalg.det(matrix_4)
print(f"Determinant of matrix_4: {matrix_4_det}")


  sample  gene_1  gene_2  gene_3
0     s1       1       4       7
1     s2       2       5       8
2     s3       3       6       9
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinant of matrix_4: 0.0


**Since we found the determinant, what does the this determinat value actually means?**



*  If det is zero, which means rows/columns are linearly dependent
*  so only with matrix with rows/colums that are linearly independent has non zero determinat

*What would this dependent/independent mean in a data?*

Let's take our above code, (cell 32);
    - There the determinant is zero
        - which means the data may not be linearly independent
             - it may be linearly dependent
                  - they depend each other



**caution**: Only with determinat only we cannot say a data is correlated/dependent in real world problems



In [ ]:
#another dataset
#converting to matrix

data_behavior = {
    "participant": ["P1", "P2", "P3", "P4"],
    "reaction_time_ms": [350, 420, 300, 390],
    "accuracy_percent": [95, 88, 100, 92],
    "trial_count": [10, 12, 9, 11]
}

#converting to table

import pandas as pd
table_3 = pd.DataFrame(data_behavior)
print(table_3)

#converting to matrix
matrix_6 = table_3.to_numpy()
print(matrix_6)

#for only generating numerical matrix
matrix_7 = table_3[["reaction_time_ms","accuracy_percent","trial_count"]].to_numpy()
print(matrix_7)
print(f"Order of the matrix_7: {matrix_7.shape}")

import numpy as np


#finding the determinant
matrix_7 = np.array(matrix_7)
matrix_7_det = np.linalg.det(matrix_7)
print(f"Determinant of matrix_7: {matrix_7_det}")


  participant  reaction_time_ms  accuracy_percent  trial_count
0          P1               350                95           10
1          P2               420                88           12
2          P3               300               100            9
3          P4               390                92           11
[['P1' 350 95 10]
 ['P2' 420 88 12]
 ['P3' 300 100 9]
 ['P4' 390 92 11]]
[[350  95  10]
 [420  88  12]
 [300 100   9]
 [390  92  11]]
Order of the matrix_7: (4, 3)


LinAlgError: Last 2 dimensions of the array must be square

**Oops! Error right!**

We should be aware that only square matrices has detrminants.

In the above practice, the matrix has the order of 4,3. so we cannot find the determinant

*small advice: Don't erase the determinant code just because you see some error in your output. Let it be. Errors are good. It will refresh your basics when you look at the code after some time*

In [ ]:
#we can use 'linalg' module to find many features of a matrix(or data)
   #inverse
   #Eigen values and Eigen vectors
   #Rank


import numpy as np

#lets find inverse of a matrix
    #key point to remember: inverse only exist for matrix with determinant having non zero value

#lets find the inverse
data_2 = [
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 1]
]

data_2 = np.array(data_2)

#determinant of the matrix
data_2_det = np.linalg.det(data_2)
print(f"Determinant of data_2 matrix: {data_2_det}")

data_2_inv = np.linalg.inv(data_2)
print(f"Inverse of the matrix data_2: {data_2_inv}")


Determinant of data_2 matrix: 4.000000000000001
Inverse of the matrix data_2: [[ 0.75 -0.25 -0.25]
 [ 0.25  0.25 -0.75]
 [-0.75  0.25  1.25]]


In [ ]:
#lets try to find the inverse of a matrix of determinant 0

data_1 = {"sample":["s1","s2","s3"],
          "gene_1":[1,2,3],
          "gene_2":[4,5,6],
          "gene_3":[7,8,9]}

#converting this to table

import pandas as pd
table_1 = pd.DataFrame(data_1)
print(table_1)

#converting the table to matrix

matrix_4 = table_1[["gene_1","gene_2","gene_3"]].to_numpy()
print(matrix_4)

#FIND THE DETERMINANT OF matrix_4

import numpy as np
matrix_4 = np.array(matrix_4)
matrix_4_det = np.linalg.det(matrix_4)
print(f"Determinant of matrix_4: {matrix_4_det}")

matrix_4_inv = np.linalg.inv(matrix_4)
print(matrix_4_inv)

  sample  gene_1  gene_2  gene_3
0     s1       1       4       7
1     s2       2       5       8
2     s3       3       6       9
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinant of matrix_4: 0.0


LinAlgError: Singular matrix

**LinAlgError: Singular matrix**



*  singular matrix are matrix with determinant zero
     - Which means their rows/columns are linearly dependent

So now we know what it means by "LinAlgError:Singular matrix"

Why don't we generate this same message rather than error in our program?

let's do it!

for this we are going to use *Try and except*


In [ ]:
#lets try to find the inverse of a matrix of determinant 0

data_1 = {"sample":["s1","s2","s3"],
          "gene_1":[1,2,3],
          "gene_2":[4,5,6],
          "gene_3":[7,8,9]}

#converting this to table

import pandas as pd
table_1 = pd.DataFrame(data_1)
print(table_1)

#converting the table to matrix

matrix_4 = table_1[["gene_1","gene_2","gene_3"]].to_numpy()
print(matrix_4)

#FIND THE DETERMINANT OF matrix_4

import numpy as np
matrix_4 = np.array(matrix_4)
matrix_4_det = np.linalg.det(matrix_4)
print(f"Determinant of matrix_4: {matrix_4_det}")

#using try except to catch the expected error
try:
    matrix_4_inv = np.linalg.inv(matrix_4)
    print(matrix_4_inv)
except:
    print("singular matrix")


  sample  gene_1  gene_2  gene_3
0     s1       1       4       7
1     s2       2       5       8
2     s3       3       6       9
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Determinant of matrix_4: 0.0
singular matrix


In [ ]:
#Now lets catch another error using try except

import numpy as np


data_3 = [[1,2],[4,5]]
data_3 = np.array(data_3)
data_3_det = np.linalg.det(data_3)
print(f"Determinant of data_3: {data_3_det}")

#in the above data
    # it is a square matrix,
    #thus we could find th determinant easily


Determinant of data_3: -2.9999999999999996


In [ ]:
#Finding Eigen values and Eigen vector
  #Eigen values represent the variance along corresponding Eigen vector
    #larger the value: more the variance along that vector
    #lesser or negative value: less the variance along that vector

import pandas as pd
import numpy as np



matrix_ex1 = [
    [4, 2, 1, 3, 5],
    [0, 1, 2, 4,5],
    [2, 0, 3, 1, 2],
    [1, 2, 0, 2, 3],
    [3, 1, 2, 0, 4]
]

matrix_ex1 = np.array(matrix_ex1)
matrix_ex1_eigenvalue, matrix_ex1_eigenvector = np.linalg.eig(matrix_ex1)
print(f"The Eigen values are: {matrix_ex1_eigenvalue}\n")
print(f"The Eigen vectors are: {matrix_ex1_eigenvector}")

#usually in data analysis, Eigen values/vectors are calculated for covariance matrix. Not raw data




The Eigen values are: [10.76442493+0.j         -1.4386426 +0.j          1.6974497 +1.63429844j
  1.6974497 -1.63429844j  1.27931826+0.j        ]

The Eigen vectors are: [[-0.64417972+0.j          0.04431886+0.j          0.53303361+0.j
   0.53303361-0.j          0.21416293+0.j        ]
 [-0.42514775+0.j          0.89875025+0.j         -0.14937535+0.45484408j
  -0.14937535-0.45484408j -0.62418856+0.j        ]
 [-0.3217333 +0.j          0.16423586+0.j         -0.20833233-0.27456754j
  -0.20833233+0.27456754j -0.56725879+0.j        ]
 [-0.32238017+0.j         -0.31743156+0.j          0.28938557+0.38622666j
   0.28938557-0.38622666j -0.27279641+0.j        ]
 [-0.4436672 +0.j         -0.25009523+0.j         -0.31768208-0.18453292j
  -0.31768208+0.18453292j  0.41027119+0.j        ]]


In [17]:
#practicing Eigen values and Eigen vectors

data_behavior = {
    "participant": ["P1", "P2", "P3", "P4"],
    "reaction_time_ms": [350, 420, 300, 390],
    "accuracy_percent": [95, 88, 100, 92],
    "trial_count": [10, 12, 9, 11],
    "response_time":[6,8,9,11]
}

import pandas as pd
import numpy as np

table_3 = pd.DataFrame(data_behavior)
print(table_3)

matrix_3 = np.array(table_3[["reaction_time_ms","accuracy_percent","trial_count","response_time"]])
print(matrix_3)

matrix_3_eigenvalue, matrix_3_eigenvector = np.linalg.eig(matrix_3)
print(f"Eigen value of the matrix_3: {matrix_3_eigenvalue}")
print(f"Eigen vector of the matrix_3:{matrix_3_eigenvector}")


  participant  reaction_time_ms  accuracy_percent  trial_count  response_time
0          P1               350                95           10              6
1          P2               420                88           12              8
2          P3               300               100            9              9
3          P4               390                92           11             11
[[350  95  10   6]
 [420  88  12   8]
 [300 100   9   9]
 [390  92  11  11]]
Eigen value of the matrix_3: [473.89524764 -20.14082747   0.60146434   3.6441155 ]
Eigen vector of the matrix_3:[[ 4.81216566e-01  1.45331176e-01 -2.95239751e-02 -3.64874714e-02]
 [ 5.48265572e-01 -6.29389404e-01  5.79692848e-04  1.14730093e-02]
 [ 4.38625622e-01  7.31293853e-01  9.98508919e-01  7.80022941e-01]
 [ 5.24826679e-01 -2.18991160e-01  4.59122756e-02  6.24580857e-01]]


In [6]:
#Eigen values and Eigen vectors

#To refresh our memory, we will start with this data
    #convert it to table
       #then to matrix
          #then we will find the Eigen values and Eigen vector

data_behavior = {
    "participant": ["P1", "P2", "P3", "P4"],
    "reaction_time_ms": [350, 420, 300, 390],
    "accuracy_percent": [95, 88, 100, 92],
    "trial_count": [10, 12, 9, 11]
}

import pandas as pd
import numpy as np

table_3 = pd.DataFrame(data_behavior)
print(table_3)

matrix_6 = np.array(table_3[["reaction_time_ms","accuracy_percent","trial_count"]])
print(matrix_6)

try:
    matrix_6_det = np.linalg.det(matrix_6)
    print(f"Determinant of matrix_6: {matrix_6_det}")
except:
    print("This is not a square matrix")

#since this is not a square matrix
  #no determinant
    #since there is no determinant
       #then there is no inverse
         #there is no eigen values or eigen vector either


  participant  reaction_time_ms  accuracy_percent  trial_count
0          P1               350                95           10
1          P2               420                88           12
2          P3               300               100            9
3          P4               390                92           11
[[350  95  10]
 [420  88  12]
 [300 100   9]
 [390  92  11]]
This is not a square matrix


In [8]:
#now let's try to find Rank

#In the above matrix, we see that we cannot calculate det,inv,eigen values or eigen vectors. since it was not a square matrix

#let's try to find it's rank

data_behavior = {
    "participant": ["P1", "P2", "P3", "P4"],
    "reaction_time_ms": [350, 420, 300, 390],
    "accuracy_percent": [95, 88, 100, 92],
    "trial_count": [10, 12, 9, 11]
}

import pandas as pd
import numpy as np

table_3 = pd.DataFrame(data_behavior)
print(table_3)

matrix_6 = np.array(table_3[["reaction_time_ms","accuracy_percent","trial_count"]])
print(matrix_6)

try:
    matrix_6_det = np.linalg.det(matrix_6)
    print(f"Determinant of matrix_6: {matrix_6_det}")
except:
    print("This is not a square matrix")

#finding rank

matrix_6_rank = np.linalg.matrix_rank(matrix_6)
print(f"Rank of the matrix: {matrix_6_rank}")

  participant  reaction_time_ms  accuracy_percent  trial_count
0          P1               350                95           10
1          P2               420                88           12
2          P3               300               100            9
3          P4               390                92           11
[[350  95  10]
 [420  88  12]
 [300 100   9]
 [390  92  11]]
This is not a square matrix
Rank of the matrix: 3


**What does it mean by Rank?**

- In the above code, Rank 3 means there are 3  columns are linearly independent, that we cannot transform one variable to another,

therefore each variable holds independent information and essential to data

In [12]:
#Now what if we take another data and find it's rank

data_example = {
    "x": [1, 2, 3, 4],
    "y": [2, 4, 6, 8],
    "z": [5, 6, 7, 8]
}

import numpy as np
import pandas as pd

table_7 =pd.DataFrame(data_example)
print(table_7)

matrix_7 = np.array(table_7[["x","y","z"]])
print(matrix_7)

try:
  matrix_7_det = np.linalg.det(matrix_7)
  print(f"Determinat of matrix_7: {matrix_7_det}")
except:
  print("This is not a square matrix")

matrix_7_rank = np.linalg.matrix_rank(matrix_7)
print(f"Rank of the matrix: {matrix_7_rank}")

#Here rank 2 means, only two columns are linearly independent.


   x  y  z
0  1  2  5
1  2  4  6
2  3  6  7
3  4  8  8
[[1 2 5]
 [2 4 6]
 [3 6 7]
 [4 8 8]]
This is not a square matrix
Rank of the matrix: 2


**Summary**

- we have learnt;

   -How to convert data into matrix


   -How to find the detrminant of that matrix

   -How to find the inverse of that matrix

   -How to find the Eigen values and Eigen vectors of that matrix
   
   -How to find the Rank of that matrix
   